erDiagram
    PESSOA {
        ENDERECO Endereco "Null or Not Null"
        VARCHAR2 email "Null or Not Null"
        VARCHAR2[] telefones "Null or Not Null"
    }

    FORNECEDOR {
        NUMBER ID PK "Not Null"
        VARCHAR2 cnpj "Not Null"
        VARCHAR2 razao_social "Not Null"
        VARCHAR2 nome_fantasia "Null or Not Null"
        COMPRA[] pedidos "Null or Not Null"
    }

    ITEM_COMPRA {
        NUMBER ID_FORNECEDOR FK "Not Null"
        PRODUTO produto FK "Not Null"
        NUMBER quantidade "Not Null"
        NUMBER preco_unidade "Not Null"
        NUMBER sub_total "Not Null"
    }

    COMPRA {
        NUMBER ID PK "Not Null"
        ITEM_COMPRA[] itens"Not Null"
        DATE data "Null or Not Null"
        NUMBER total "Not Null"
    }

    CLIENTE {
        NUMBER ID PK "Not Null"
        VARCHAR2 cpf "Not Null"
        VARCHAR2 nome "Not Null"
        Venda[] pedidos "Null or Not Null"
    }

    ITEM_VENDA {
        NUMBER ID_CLIENTE FK "Not Null"
        PRODUTO produto FK "Not Null"
        NUMBER quantidade "Not Null"
        NUMBER preco_unidade "Not Null"
        NUMBER sub_total "Not Null"
    }

    VENDA {
        NUMBER ID PK "Not Null"
        ITEM_VENDA[] itens"Not Null"
        DATE data "Null or Not Null"
        NUMBER total "Not Null"
    }

    ENDERECO {
        VARCHAR2 cep "Null or Not Null"
        VARCHAR2 logradouro "Null or Not Null"
        NUMBER numero "Null or Not Null"
        VARCHAR2 complemento "Null or Not Null"
        VARCHAR2 bairro "Null or Not Null"
        VARCHAR2 cidade "Null or Not Null"
        VARCHAR2 estado "Null or Not Null"
    }

    PRODUTO {
        NUMBER ID_PRODUTO PK "Not Null"
        VARCHAR2 nome "Not Null"
        NUMBER preco "Not Null"
        VARCHAR2 descricao "Null or Not Null"
    }

    PESSOA ||--|| FORNECEDOR : ""
    PESSOA ||--|| CLIENTE : ""

    FORNECEDOR ||--|{ COMPRA : "compramos de"
    COMPRA ||--|{ ITEM_COMPRA : "compõem"

    CLIENTE ||--O{ VENDA : "vendemos para"
    VENDA ||--|{ ITEM_VENDA : "compõem"

    ITEM_COMPRA }|--|| PRODUTO : "compõem"
    ITEM_VENDA }|--|| PRODUTO : "compõem"