version: '3.8'
services:
  app:
    build: .
    depends_on:
      database:
        condition: service_healthy
    volumes:
      - .:/app

  database:
    image: container-registry.oracle.com/database/free:latest
    container_name: trabalhosql-oracle-db
    ports:
      - "1521:1521"
    environment:
      ORACLE_PWD: Trabalho204012
    volumes:
      - oracle_data:/opt/oracle/oradata
    healthcheck:
      test: ["CMD-SHELL", "tnsping FREEPDB1"]
      interval: 10s
      timeout: 10s
      retries: 10

volumes:
  oracle_data:
