erDiagram
    PESSOA {
        
    }

    FORNECEDOR {
        Integer ID PK "Not Null"
    }

    ITEM_COMPRA {
        Integer ID PK "Not Null"
    }

    COMPRA {
        Integer ID PK "Not Null"
    }

    CLIENTE {
        Integer ID PK "Not Null"
    }

    ITEM_VENDA {
        Integer ID PK "Not Null"
    }

    VENDA {
        Integer ID PK "Not Null"
    }